### ISSUE TITLE
Cannot build extensions

### ISSUE THREAD

**Issue by Kinzi** [directus/extension-toolkit#2]
Building the interface creates an error.

1. Reproduce
- `directus-extensions create interface myinterface`
- `cd myinterface`
- `npm run build`

2. Output

```
> myinterface@1.0.0 build /directusapi/extensions/interfaces/myinterface
> directus-extensions build

🚨  /directusapi/extensions/interfaces/myinterface/src/display.vue:

Vue packages version mismatch:

- vue@2.5.17 (/directusapi/extensions/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 /directusapi/extensions/interfaces/myinterface/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


Vue packages version mismatch:

- vue@2.5.17 (/directusapi/extensions/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/directusapi/extensions/interfaces/myinterface/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/directusapi/extensions/interfaces/myinterface/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (/usr/local/lib/node_modules/@directus/extension-toolkit/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at localRequire (/usr/local/lib/node_modules/@directus/extension-toolkit/node_modules/parcel-bundler/src/utils/localRequire.js:11:10)
    at <anonymous>
directus-extensions build [input] [output]

Build the source files for production use

Optionen:
  --version  Version anzeigen                                          [boolean]
  --help     Hilfe anzeigen                                            [boolean]

{ message: '\n\nVue packages version mismatch:\n\n- vue@2.5.17 (/directusapi/extensions/node_modules/vue/dist/vue.runtime.common.js)\n- vue-template-compiler@2.6.10 (/directusapi/extensions/interfaces/myinterface/node_modules/vue-template-compiler/package.json)\n\nThis may cause things to work incorrectly. Make sure to use the same version for both.\nIf you are using vue-loader@>=10.0, simply update vue-template-compiler.\nIf you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.\n',
  stack: 'Error: \n\nVue packages version mismatch:\n\n- vue@2.5.17 (/directusapi/extensions/node_modules/vue/dist/vue.runtime.common.js)\n- vue-template-compiler@2.6.10 (/directusapi/extensions/interfaces/myinterface/node_modules/vue-template-compiler/package.json)\n\nThis may cause things to work incorrectly. Make sure to use the same version for both.\nIf you are using vue-loader@>=10.0, simply update vue-template-compiler.\nIf you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.\n\n    at Object.<anonymous> (/directusapi/extensions/interfaces/myinterface/node_modules/vue-template-compiler/index.js:10:9)\n    at Module._compile (/usr/local/lib/node_modules/@directus/extension-toolkit/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at localRequire (/usr/local/lib/node_modules/@directus/extension-toolkit/node_modules/parcel-bundler/src/utils/localRequire.js:11:10)\n    at <anonymous>',
  name: 'Error',
  fileName: '/directusapi/extensions/interfaces/myinterface/src/display.vue' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myinterface@1.0.0 build: `directus-extensions build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myinterface@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2019-04-29T11_16_55_899Z-debug.log
```

**Comment by Kinzi** [comment]
Solved by making sure to use the latest version of the API in my git project.
